name: Deploy Angular Application to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20  # Ensure compatibility with Angular 17

    - name: Install dependencies
      run: npm install

    - name: Build the Angular app
      run: npm run build -- --configuration production

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/mohitsoni2000/mohit-portfolio.git

    - name: Deploy to GitHub Pages
      env:
        CI: true
      run: |
        npm run deploy
