name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --output-path docs --base-href /docs/

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v5.0.0
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          publish_dir: ./docs  # Ensure this path is correct
